#!/bin/sh
files="debian.txt arch.txt gentoo.txt slackware.txt fedora.txt other.txt"
for file in $files; do
    echo $file": $(cat "$file" | wc -l)"
done
total_lines=$(for file in $files ; do cat "$file" ; done | wc -l)
echo "total: "$total_lines
