#!/bin/sh
files="debian arch gentoo slackware other"
for file in $files; do
    echo $file": $(cat "$file" | wc -l)"
done
total_lines=$(for file in $files ; do cat "$file" | awk '{sum+=$0} END {print sum}' ; done)
echo "total: "$total_lines
